# This is the SAM template that represents the architecture of your serverless application
# https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/serverless-sam-template-basics.html

# The AWSTemplateFormatVersion identifies the capabilities of the template
# https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/format-version-structure.html
AWSTemplateFormatVersion: 2010-09-09
Description: >-
  This app will manage all Risto data

# Transform section specifies one or more macros that AWS CloudFormation uses to process your template
# https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/transform-section-structure.html
Transform: AWS::Serverless-2016-10-31

# Shared configuration for all resources, more in
# https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    # The PermissionsBoundary allows users to safely develop with their function's permissions constrained
    # to their current application. All the functions and roles in this application have to include it and
    # it has to be manually updated when you add resources to your application.
    # More information in https://docs.aws.amazon.com/IAM/latest/UserGuide/access_policies_boundaries.html
    PermissionsBoundary: !Sub "arn:${AWS::Partition}:iam::${AWS::AccountId}:policy/${AppId}-${AWS::Region}-PermissionsBoundary"

Parameters:
  AppId:
    Type: String

# Resources declares the AWS resources that you want to include in the stack
# https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/resources-section-structure.html
Resources:
  # Each Lambda function is defined by properties:
  # https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction

  # This is a Lambda function config associated with the source code: hello-from-lambda.js
  helloFromLambdaFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./
      Handler: src/handlers/hello-from-lambda.helloFromLambdaHandler
      Runtime: nodejs10.x
      MemorySize: 128
      Timeout: 60
      Description: A Lambda function that returns a static string.
      Policies:
        # Give Lambda basic execution Permission to the helloFromLambda
        - AWSLambdaBasicExecutionRole
  listAllPayments:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./
      Handler: src/delivery/payment/handler/payment_list_all.listAll
      Runtime: nodejs10.x
      MemorySize: 128
      Timeout: 60
      Description: This function return all method payments.
      Policies:
        # Give Lambda basic execution Permission to the helloFromLambda
        - AWSLambdaBasicExecutionRole
  listLocalBySignature:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./
      Handler: src/delivery/local/handler/local_list_by_signature.listLocalBySignature
      Runtime: nodejs10.x
      MemorySize: 128
      Timeout: 60
      Description: This function return all locals by signature.
      Policies:
        # Give Lambda basic execution Permission to the helloFromLambda
        - AWSLambdaBasicExecutionRole
  listLocalByCriteria:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./
      Handler: src/delivery/local/handler/local_list.listLocal
      Runtime: nodejs10.x
      MemorySize: 128
      Timeout: 60
      Description: This function return all locals by criteria.
      Policies:
        # Give Lambda basic execution Permission to the helloFromLambda
        - AWSLambdaBasicExecutionRole
  addPersonalToLocal:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./
      Handler: src/delivery/personal/handler/personal_add.addPersonal
      Runtime: nodejs10.x
      MemorySize: 128
      Timeout: 60
      Description: This function add a personal to a local.
      Policies:
        # Give Lambda basic execution Permission to the helloFromLambda
        - AWSLambdaBasicExecutionRole
  removePersonal:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./
      Handler: src/delivery/personal/handler/personal_remove.removePersonal
      Runtime: nodejs10.x
      MemorySize: 128
      Timeout: 60
      Description: This function remove personal.
      Policies:
        # Give Lambda basic execution Permission to the helloFromLambda
        - AWSLambdaBasicExecutionRole
  listPersonalLocal:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./
      Handler: src/delivery/personal/handler/personal_list.listPersonal
      Runtime: nodejs10.x
      MemorySize: 128
      Timeout: 60
      Description: This function list all personal by local.
      Policies:
        # Give Lambda basic execution Permission to the helloFromLambda
        - AWSLambdaBasicExecutionRole
  findLocal:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./
      Handler: src/delivery/local/handler/local_find.findLocal
      Runtime: nodejs10.x
      MemorySize: 128
      Timeout: 60
      Description: This function return one local.
      Policies:
        # Give Lambda basic execution Permission to the helloFromLambda
        - AWSLambdaBasicExecutionRole
  getLocalDeliveryPrice:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./
      Handler: src/delivery/local/handler/local_get_delivery_price.getLocalDeliveryPrice
      Runtime: nodejs10.x
      MemorySize: 128
      Timeout: 60
      Description: This function return price for a local.
      Policies:
        # Give Lambda basic execution Permission to the helloFromLambda
        - AWSLambdaBasicExecutionRole
  listLocalPayments:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./
      Handler: src/delivery/payment/handler/payment_list_by_local.listByLocal
      Runtime: nodejs10.x
      MemorySize: 128
      Timeout: 60
      Description: This function return local payments.
      Policies:
        # Give Lambda basic execution Permission to the helloFromLambda
        - AWSLambdaBasicExecutionRole
  listLocalItems:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./
      Handler: src/delivery/item/handler/item_list_by_local.listItemsByLocal
      Runtime: nodejs10.x
      MemorySize: 128
      Timeout: 60
      Description: This function return all local items.
      Policies:
        # Give Lambda basic execution Permission to the helloFromLambda
        - AWSLambdaBasicExecutionRole
  addLocalItem:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./
      Handler: src/delivery/item/handler/item_add.addItem
      Runtime: nodejs10.x
      MemorySize: 128
      Timeout: 60
      Description: This function add one item.
      Policies:
        # Give Lambda basic execution Permission to the helloFromLambda
        - AWSLambdaBasicExecutionRole
  updateItem:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./
      Handler: src/delivery/item/handler/item_update.updateItem
      Runtime: nodejs10.x
      MemorySize: 128
      Timeout: 60
      Description: This function update a item.
      Policies:
        # Give Lambda basic execution Permission to the helloFromLambda
        - AWSLambdaBasicExecutionRole
  removeItem:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./
      Handler: src/delivery/item/handler/item_remove.removeItem
      Runtime: nodejs10.x
      MemorySize: 128
      Timeout: 60
      Description: This function remove a item.
      Policies:
        # Give Lambda basic execution Permission to the helloFromLambda
        - AWSLambdaBasicExecutionRole
  changeAvialableItem:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./
      Handler: src/delivery/item/handler/item_change_available.changeItemAvailable
      Runtime: nodejs10.x
      MemorySize: 128
      Timeout: 60
      Description: This function change avialable a item.
      Policies:
        # Give Lambda basic execution Permission to the helloFromLambda
        - AWSLambdaBasicExecutionRole
  getItemViews:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./
      Handler: src/delivery/item/handler/item_get_views.getItemViews
      Runtime: nodejs10.x
      MemorySize: 128
      Timeout: 60
      Description: This function return total views for one item.
      Policies:
        # Give Lambda basic execution Permission to the helloFromLambda
        - AWSLambdaBasicExecutionRole
  addItemView:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./
      Handler: src/delivery/item/handler/item_add_view.addItemView
      Runtime: nodejs10.x
      MemorySize: 128
      Timeout: 60
      Description: This function add one view to item.
      Policies:
        # Give Lambda basic execution Permission to the helloFromLambda
        - AWSLambdaBasicExecutionRole
  search:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./
      Handler: src/delivery/search/handler/search_list.search
      Runtime: nodejs10.x
      MemorySize: 128
      Timeout: 60
      Description: This function return locals or items by query.
      Policies:
        # Give Lambda basic execution Permission to the helloFromLambda
        - AWSLambdaBasicExecutionRole
  listUserProfiles:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./
      Handler: src/delivery/profile/handler/profile_list_by_user.listProfilesByUser
      Runtime: nodejs10.x
      MemorySize: 128
      Timeout: 60
      Description: This function return all user profiles.
      Policies:
        # Give Lambda basic execution Permission to the helloFromLambda
        - AWSLambdaBasicExecutionRole
  addUserProfile:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./
      Handler: src/delivery/profile/handler/profile_add.addProfile
      Runtime: nodejs10.x
      MemorySize: 128
      Timeout: 60
      Description: This function add a profile.
      Policies:
        # Give Lambda basic execution Permission to the helloFromLambda
        - AWSLambdaBasicExecutionRole
  removeUserProfile:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./
      Handler: src/delivery/profile/handler/profile_remove.removeProfile
      Runtime: nodejs10.x
      MemorySize: 128
      Timeout: 60
      Description: This function remove a profile.
      Policies:
        # Give Lambda basic execution Permission to the helloFromLambda
        - AWSLambdaBasicExecutionRole
  updateUserProfile:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./
      Handler: src/delivery/profile/handler/profile_update.updateProfile
      Runtime: nodejs10.x
      MemorySize: 128
      Timeout: 60
      Description: This function update a profile.
      Policies:
        # Give Lambda basic execution Permission to the helloFromLambda
        - AWSLambdaBasicExecutionRole
  qualification:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./
      Handler: src/delivery/product/handler/product_rate.rateProduct
      Runtime: nodejs10.x
      MemorySize: 128
      Timeout: 60
      Description: This function rate some.
      Policies:
        # Give Lambda basic execution Permission to the helloFromLambda
        - AWSLambdaBasicExecutionRole
  updateLocal:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./
      Handler: src/delivery/local/handler/local_update.updateLocal
      Runtime: nodejs10.x
      MemorySize: 128
      Timeout: 60
      Description: This function update local.
      Policies:
        # Give Lambda basic execution Permission to the helloFromLambda
        - AWSLambdaBasicExecutionRole
  renameLocal:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./
      Handler: src/delivery/local/handler/local_rename.renameLocal
      Runtime: nodejs10.x
      MemorySize: 128
      Timeout: 60
      Description: This function update local.
      Policies:
        # Give Lambda basic execution Permission to the helloFromLambda
        - AWSLambdaBasicExecutionRole
  removeLocal:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./
      Handler: src/delivery/local/handler/local_remove.removeLocal
      Runtime: nodejs10.x
      MemorySize: 128
      Timeout: 60
      Description: This function remove local.
      Policies:
        # Give Lambda basic execution Permission to the helloFromLambda
        - AWSLambdaBasicExecutionRole
  listRecordLocal:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./
      Handler: src/delivery/record/handler/record_list.listRecord
      Runtime: nodejs10.x
      MemorySize: 128
      Timeout: 60
      Description: This function return records by local.
      Policies:
        # Give Lambda basic execution Permission to the helloFromLambda
        - AWSLambdaBasicExecutionRole
  listUser:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./
      Handler: src/delivery/user/handler/user_list.listUser
      Runtime: nodejs10.x
      MemorySize: 128
      Timeout: 60
      Description: This function return a list of users.
      Policies:
        # Give Lambda basic execution Permission to the helloFromLambda
        - AWSLambdaBasicExecutionRole
  isFollowing:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./
      Handler: src/delivery/user/handler/user_id_following.isFollowing
      Runtime: nodejs10.x
      MemorySize: 128
      Timeout: 60
      Description: This function return a list of users.
      Policies:
        # Give Lambda basic execution Permission to the helloFromLambda
        - AWSLambdaBasicExecutionRole
  FollowLocal:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./
      Handler: src/delivery/user/handler/user_following.followLocal
      Runtime: nodejs10.x
      MemorySize: 128
      Timeout: 60
      Description: This function return a list of users.
      Policies:
        # Give Lambda basic execution Permission to the helloFromLambda
        - AWSLambdaBasicExecutionRole
  listNotifications:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./
      Handler: src/delivery/notification/handler/notification_list.listNotification
      Runtime: nodejs10.x
      MemorySize: 128
      Timeout: 60
      Description: This function return a list of notifications by user.
      Policies:
        # Give Lambda basic execution Permission to the helloFromLambda
        - AWSLambdaBasicExecutionRole
  checkNotification:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./
      Handler: src/delivery/notification/handler/notification_check.checkNotification
      Runtime: nodejs10.x
      MemorySize: 128
      Timeout: 60
      Description: This function change notification state.
      Policies:
        # Give Lambda basic execution Permission to the helloFromLambda
        - AWSLambdaBasicExecutionRole
  listClientDeliveries:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./
      Handler: src/delivery/delivery/handler/delivery_lister_by_client.listDeliveryByClient
      Runtime: nodejs10.x
      MemorySize: 128
      Timeout: 60
      Description: This function return a list of client orders.
      Policies:
        # Give Lambda basic execution Permission to the helloFromLambda
        - AWSLambdaBasicExecutionRole
  listLocalDeliveries:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./
      Handler: src/delivery/delivery/handler/delivery_lister_by_local.listDeliveryByLocal
      Runtime: nodejs10.x
      MemorySize: 128
      Timeout: 60
      Description: This function return a list of local orders.
      Policies:
        # Give Lambda basic execution Permission to the helloFromLambda
        - AWSLambdaBasicExecutionRole
  changeDeliveryState:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./
      Handler: src/delivery/delivery/handler/delivery_state_change.changeDeliveryState
      Runtime: nodejs10.x
      MemorySize: 128
      Timeout: 60
      Description: This function change delivery state.
      Policies:
        # Give Lambda basic execution Permission to the helloFromLambda
        - AWSLambdaBasicExecutionRole
  addDelivery:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./
      Handler: src/delivery/delivery/handler/delivery_add.addDelivery
      Runtime: nodejs10.x
      MemorySize: 128
      Timeout: 60
      Description: This function register one delivery.
      Policies:
        # Give Lambda basic execution Permission to the helloFromLambda
        - AWSLambdaBasicExecutionRole
  removeDelivery:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./
      Handler: src/delivery/delivery/handler/delivery_remove.removeDelivery
      Runtime: nodejs10.x
      MemorySize: 128
      Timeout: 60
      Description: This function remove one delivery.
      Policies:
        # Give Lambda basic execution Permission to the helloFromLambda
        - AWSLambdaBasicExecutionRole
  authVerifyClient:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./
      Handler: src/auth/token/handler/auth_verify_client_handler.authVerifyHandler
      Runtime: nodejs10.x
      MemorySize: 128
      Timeout: 60
      Description: A Lambda function that authorizer risto.
      Policies:
        # Give Lambda basic execution Permission to the helloFromLambda
        - AWSLambdaBasicExecutionRole
  authVerifyManager:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./
      Handler: src/auth/token/handler/auth_verify_manager_handler.authVerifyHandler
      Runtime: nodejs10.x
      MemorySize: 128
      Timeout: 60
      Description: A Lambda function that authorizer risto.
      Policies:
        # Give Lambda basic execution Permission to the helloFromLambda
        - AWSLambdaBasicExecutionRole
  login:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./
      Handler: src/auth/token/handler/auth_login_handler.authLoginHandler
      Runtime: nodejs10.x
      MemorySize: 128
      Timeout: 60
      Description: A Lambda function that authorizer risto.
      Policies:
        # Give Lambda basic execution Permission to the helloFromLambda
        - AWSLambdaBasicExecutionRole
